# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Dumello' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for Facebook
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    
    # Required by RNFirebase
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'

    target 'DumelloTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
